name:  build and test features branchs

on:
  push:
    branches:
      - feature/*

jobs:
  build-feature:
    runs-on: windows-latest
    steps:
      - name: pull and checkout from git repository
        uses: actions/checkout@v4 

      - name: Checkout completed
        run: echo "Checked out repository"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
         node-version: 18 

      - name: Install dependencies
        run: npm install  

      - name: Running Unit Tests
        run: |
          ng test --watch=false
          ng build